___Globals = {
    --SpawnPart = PopConstructions.SpawnPart,
    SpawnConstruction = PopConstructions.SpawnConstruction,
    DestroyPart = PopConstructions.DestroyPart,
    DestroyConstruction = PopConstructions.DestroyConstruction,
    DestroyConstructions = PopConstructions.DestroyConstructions,
    DuplicatePart  = PopConstructions.DuplicatePart ,
    DuplicateConstruction  = PopConstructions.DuplicateConstruction ,

}
Category_heap = {
    "Suspension",
    "Pulleys",
    "Blocks",
    "Brakes & Clutches",
    "Combustion Engines",
    "Connectors",
    "Gears",
    "Linear Actuators",
    "Motors",
    "Pipes"
}
ICategories = {
    {
        "SpringDamper Ball Large Barrel",
        "SpringDamper Ball Large Piston",
        "SpringDamper Ball Medium Barrel",
        "SpringDamper Ball Medium Piston",
        "SpringDamper Ball Small Barrel",
        "SpringDamper Ball Small Piston",
        "SpringDamper Ball Small Strong Barrel",
        "SpringDamper Ball Small Strong Piston",
        "SpringDamper Large Barrel",
        "SpringDamper Large Piston",
        "SpringDamper Medium Barrel",
        "SpringDamper Medium Piston",
        "SpringDamper Small Barrel",
        "SpringDamper Small Piston",
        "SpringDamper Small Strong Barrel",
        "SpringDamper Small Strong Piston",
        "Torsion SpringDamper Axle",
        "Torsion SpringDamper Block",
    },--suspension
    {
        "Pulley 1x1",
        "Pulley 1x1 5",
        "Pulley 1x2",
        "Pulley 1x2 5",
        "Pulley 1x3",
        "Pulley 1x4",
        "Pulley 1x5",
        "Pulley 1x6",
        "Pulley 1x7",
        "Pulley Differential x4",
        "Pulley Differential x6",
    },--pulleys
    {
        "W45 Beam",
        "V90 Beam",
        "V60 Beam",
        "Tile Offset 2x2",
        "Tile Offset 1x2",
        "Sphere Resizable",
        "Plate U Resizable",
        "Plate Resizable",
        "Plate Labelled Resizable",
        "Plate L Resizable",
        "Gusset x1",
        "Cylinder Resizable",
        "Circle Plate Resizable",
        "Block Resizable",
        "Beam Scaffold Resizable",
        "Beam Rounded Resizable",
        "Beam Resizable",
        "Angle157 5 Beam",
        "Angle150 Beam",
        "Angle135 Beam",
        "Angle120 Beam",
        "Angle9x40 Beam",
        "Angle5x72 Beam",
        "Angle3x120 Beam",
        "Beam Half Rounded Resizable",
    },--blocks
    {
        "Ratchet Block",
        "Ratchet Axle",
        "Clutch Ring Gear x4",
        "Clutch Ring Gear x3",
        "Clutch Centrifugal x3",
        "Clutch Centrifugal x2",
        "Clutch Centrifugal Ring Gear x3",
        "Brake Disk x4",
        "Brake Disk x3",
    },--Brakes & Clutches
    {
        "Engine ThrottleBody x1",
        "Engine Head x2",
        "Engine Head x1",
        "Engine Cylinder 2x2 Translucent",
        "Engine Cylinder 2x2",
        "Engine Cylinder 1x1 Translucent",
        "Engine Cylinder 1x1",
        "Engine Crank x2",
        "Engine Crank x1",
        "Engine Crank Rear x2 Axle Resizable",
        "Engine Crank Rear x1 Axle Resizable",
        "Engine Crank Nose Axle Resizable",
    },--Combustion Engines
    {
        "SliderRail Resizable",
        "Rotor 4",
        "Rotor 3",
        "Rotor 2",
        "Connector UJYoke Axle Resizable",
        "Connector Plate Axle Resizable",
        "Connector Plate2 Axle Resizable",
        "Connector Pin",
        "Connector PerpSocket Axle Resizable",
        "Connector PerpSocket",
        "Connector ParaSocket Axle Resizable",
        "Connector ParaSocket",
        "Connector Offset 3 Hole x5",
        "Connector Offset 3 Hole x3",
        "Connector KnuckleJointOuter180 Axle Resizable",
        "Connector KnuckleJointOuter180",
        "Connector KnuckleJointOuter90 Axle Resizable",
        "Connector KnuckleJointOuter90",
        "Connector KnuckleJointInner Axle Resizable",
        "Connector KnuckleJointInner",
        "Connector CVJointOuter Axle Resizable",
        "Connector CVJointOuter",
        "Connector CVJointInner Axle Resizable",
        "Connector CVJointInner",
        "Connector Ball Axle Resizable",
        "Connector Ball",
        "Connector AngleLimiter Block",
        "Connector AngleLimiter Axle",
        "Connector 2 Hole SliderRail Resizable",
        "Connector 2 Hole Plate Resizable",
        "Connector 2 Hole Para SliderRail Resizable",
        "Connector 2 Hole Para Plate Resizable",
        "Connector 2 Hole Axle Resizable",
        "Connector 2 Hole Axle Perp Resizable",
        "Connector 1 Hole SliderRail Resizable",
        "Connector 1 Hole Plate Resizable",
        "Connector 1 Hole Para SliderRail Resizable",
        "Connector 1 Hole Para Plate Resizable",
        "Connector 1 Hole Axle Resizable",
        "Axle Scaffold Resizable",
        "Axle Resizable",
    },--connectors
    {
        "Gear Worm 1T CW 7x1",
        "Gear Worm 1T CW 1x1",
        "Gear Worm 1T CW 3x1",
        "Gear Worm 1T CCW 3x1",
        "Gear Worm 1T CCW 1x1",
        "Gear Worm 1T CCW 7x1",
    }, -- worm gears
    {
        "Gear Spur Ratchet 24T 1x3",
        "Gear Spur Ratchet 20T 1x2.5",
        "Gear Spur Ratchet 16T 1x2",
        "Gear Spur Ratchet 12T 1x1.5",
        "Gear Spur Ratchet 8T 1x1",
    }, -- Gear Ratchets
    {
        "Gear Spur Clutch 24T 1x3",
        "Gear Spur Clutch 20T 1x2.5",
        "Gear Spur Clutch 16T 1x2",
        "Gear Spur Clutch 12T 1x1.5",
        "Gear Spur Clutch 8T 1x1",
        },
    {
        "Gear Spur 72T 1x9",
        "Gear Spur 64T 1x8",
        "Gear Spur 56T 1x7",
        "Gear Spur 48T 1x6",
        "Gear Spur 40T 1x5",
        "Gear Spur 36T 1x4.5",
        "Gear Spur 32T 1x4",
        "Gear Spur 28T 1x3.5",
        "Gear Spur 24T 1x3",
        "Gear Spur 22T 1x2.75",
        "Gear Spur 20T 1x2.5",
        "Gear Spur 18T 1x2.25",
        "Gear Spur 16T 1x2",
        "Gear Spur 14T 1x1.75",
        "Gear Spur 12T 1x1.5",
        "Gear Spur 10T 1x1.25",
        "Gear Spur 8T 1x1",
        "Gear Rack x7",
        "Gear Rack x3",
        "Gear Rack 2 Hole SliderRail x13",
        "Gear Rack 2 Hole SliderRail x7",
        "Gear Rack 2 Hole SliderRail x5",
        "Gear Rack 2 Hole SliderRail x3",
        "Gear Rack 2 Ball SliderRail x7",
        "Gear Rack 2 Ball SliderRail x5",
        "Gear Rack 2 Ball SliderRail x3",
        "Gear Differential Spur 48T",
        "Gear Differential Spur 32T",
        "Gear Differential Crown 48T",
        "Gear Differential Crown 32T", 
        "Gear Crown Lo 48T 1x6",
        "Gear Crown Lo 40T 1x5",
        "Gear Crown Lo 32T 1x4",
        "Gear Crown Lo 24T 1x3",
        "Gear Crown Lo 16T 1x2",
        "Gear Crown Hi 48T 1x6",
        "Gear Crown Hi 40T 1x5",
        "Gear Crown Hi 32T 1x4",
        "Gear Crown Hi 24T 1x3",
        "Gear Crown Hi 16T 1x2",
        "Gear Bevel Lo 48T 1x6",
        "Gear Bevel Lo 40T 1x5",
        "Gear Bevel Lo 32T 1x4",
        "Gear Bevel Lo 24T 1x3",
        "Gear Bevel Lo 16T 1x2",
        "Gear Bevel Hi 48T 1x6",
        "Gear Bevel Hi 40T 1x5",
        "Gear Bevel Hi 32T 1x4",
        "Gear Bevel Hi 24T 1x3",
        "Gear Bevel Hi 16T 1x2",
    },
    {
        "Light UprightRound x2",
        "Light UprightRound x1 5",
        "Light UprightRect x2",
        "Light UprightRect x1 5",
        "Light Rect 2x2",
        "Light Rect 1x2",
        "Light Cone x1",
    },
    {
        "LinearActuator Small Piston",
        "LinearActuator Small Barrel",
        "LinearActuator Medium Piston",
        "LinearActuator Medium Barrel",
        "LinearActuator LargeLong Piston",
        "LinearActuator LargeLong Barrel",
        "LinearActuator Large Piston",
        "LinearActuator Large Barrel",
        "LinearActuator Ball Small Piston",
        "LinearActuator Ball Small Barrel",
        "LinearActuator Ball Medium Piston", 
        "LinearActuator Ball Medium Barrel",
        "LinearActuator Ball LargeLong Piston",
        "LinearActuator Ball LargeLong Barrel",
        "LinearActuator Ball Large Piston",
        "LinearActuator Ball Large Barrel",
    },
    {
        "Motor Stepper Small",
        "Motor Stepper Medium",
        "Motor Starter Small",
        "Motor Servo Small",
        "Motor Servo Medium",
        "Motor Servo Continuous Small",
        "Motor Servo Continuous Medium",
        "Motor Electric Small",
        "Motor Electric Medium",
        "Motor Electric Large",
    },
    {
        "Pipe Tee Small",
        "Pipe Tee 90 Small",
        "Pipe Tee 90",
        "Pipe Tee",
        "Pipe Straight Resizable",
        "Pipe Cross Small",
        "Pipe Corner 90 Small",
        "Pipe Cross",
        "Pipe Corner Small",
        "Pipe Corner 90",
        "Pipe Corner",
        "Pipe Clamped",
    },
    {
        "Solar Panel 25x15",
        "Solar Panel 15x9",
        "Solar Panel 9x5",
        "Generator Alternator Medium",
        "Battery 15x9",
        "Battery 9x5",
        "Battery 4x3",
        "Battery 3x2 5",
        "Battery 2x1 5",
    },
    {
        "Traffic Cone 4x6",
        "Traffic Barrier Concrete 10x30",
        "Football",
    },
}
___Globals.Category_heap = Category_heap
___Globals.Categories = Categories
___Globals.ICategories = ICategories
___Globals.Heap = Heap
function SpawnPart(AssetName, position, rotation, size)
    local parts = {  }
    local p = nil
    for part in Parts.Instances do
        parts[part.ID] = part
    end
    PopConstructions.SpawnPart( AssetName, position, rotation )
    for part in Parts.Instances do
        if not parts[part.ID] then
            p = part
        end
    end
    
    p.SetSize( size )
    return p
end
___Globals.SpawnPart = SpawnPart
return ___Globals