Keylib = {}
Keylib.Keys = {
    "backspace",
    "delete",
    "tab",
    "clear",
    "return",
    "pause",
    "escape",
    "space",
    "[0]",
    "[1]",
    "[2]",
    "[3]",
    "[4]",
    "[5]",
    "[6]",
    "[7]",
    "[8]",
    "[9]",
    "[/]",
    "[*]",
    "[-]",
    "[+]",
    "[.]",
    "equals",
    "enter",
    "up",
    "down",
    "right",
    "left",
    "insert",
    "home",
    "end",
    "page up",
    "page down",
    "f1",
    "f2",
    "f3",
    "f4",
    "f5",
    "f6",
    "f7",
    "f8",
    "f9",
    "f10",
    "f11",
    "f12",
    "f13",
    "f14",
    "f15",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "-",
    "=",
    "`",
    "~",
    "!",
    "@",
    "#",
    "$",
    "%",
    "^",
    "&",
    "*",
    "(",
    ")",
    "_",
    "+",
    "[",
    "]",
    "{",
    "}",
    "\\",
    "|",
    ";",
    "'",
    ":",
    "\"",
    ",",
    ".",
    "/",
    "<",
    ">",
    "?",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "numlock",
    "caps lock",
    "scroll lock",
    "right shift",
    "left shift",
    "right ctrl",
    "left ctrl",
    "right alt",
    "left alt",
    "right cmd",
    "left cmd",
    "right super",
    "left super",
    "alt gr",
    "compose",
    "help",
    "print screen",
    "sys req",
    "break",
    "menu",
    "power",
    "euro",
    "undo",
    "mouse 0",
    "mouse 1",
    "mouse 2",
    "mouse 3",
    "mouse 4",
    "mouse 5",
    "mouse 6",
    "joystick button 0",
    "joystick button 1",
    "joystick button 2",
    "joystick button 3",
    "joystick button 4",
    "joystick button 5",
    "joystick button 6",
    "joystick button 7",
    "joystick button 8",
    "joystick button 9",
    "joystick button 10",
    "joystick button 11",
    "joystick button 12",
    "joystick button 13",
    "joystick button 14",
    "joystick button 15",
    "joystick button 16",
    "joystick button 17",
    "joystick button 18",
    "joystick button 19",
    "joystick 1 button 0",
    "joystick 1 button 1",
    "joystick 1 button 2",
    "joystick 1 button 3",
    "joystick 1 button 4",
    "joystick 1 button 5",
    "joystick 1 button 6",
    "joystick 1 button 7",
    "joystick 1 button 8",
    "joystick 1 button 9",
    "joystick 1 button 10",
    "joystick 1 button 11",
    "joystick 1 button 12",
    "joystick 1 button 13",
    "joystick 1 button 14",
    "joystick 1 button 15",
    "joystick 1 button 16",
    "joystick 1 button 17",
    "joystick 1 button 18",
    "joystick 1 button 19",
    "joystick 2 button 0",
    "joystick 2 button 1",
    "joystick 2 button 2",
    "joystick 2 button 3",
    "joystick 2 button 4",
    "joystick 2 button 5",
    "joystick 2 button 6",
    "joystick 2 button 7",
    "joystick 2 button 8",
    "joystick 2 button 9",
    "joystick 2 button 10",
    "joystick 2 button 11",
    "joystick 2 button 12",
    "joystick 2 button 13",
    "joystick 2 button 14",
    "joystick 2 button 15",
    "joystick 2 button 16",
    "joystick 2 button 17",
    "joystick 2 button 18",
    "joystick 2 button 19",
    "joystick 3 button 0",
    "joystick 3 button 1",
    "joystick 3 button 2",
    "joystick 3 button 3",
    "joystick 3 button 4",
    "joystick 3 button 5",
    "joystick 3 button 6",
    "joystick 3 button 7",
    "joystick 3 button 8",
    "joystick 3 button 9",
    "joystick 3 button 10",
    "joystick 3 button 11",
    "joystick 3 button 12",
    "joystick 3 button 13",
    "joystick 3 button 14",
    "joystick 3 button 15",
    "joystick 3 button 16",
    "joystick 3 button 17",
    "joystick 3 button 18",
    "joystick 3 button 19",
    "joystick 4 button 0",
    "joystick 4 button 1",
    "joystick 4 button 2",
    "joystick 4 button 3",
    "joystick 4 button 4",
    "joystick 4 button 5",
    "joystick 4 button 6",
    "joystick 4 button 7",
    "joystick 4 button 8",
    "joystick 4 button 9",
    "joystick 4 button 10",
    "joystick 4 button 11",
    "joystick 4 button 12",
    "joystick 4 button 13",
    "joystick 4 button 14",
    "joystick 4 button 15",
    "joystick 4 button 16",
    "joystick 4 button 17",
    "joystick 4 button 18",
    "joystick 4 button 19",
    "joystick 5 button 0",
    "joystick 5 button 1",
    "joystick 5 button 2",
    "joystick 5 button 3",
    "joystick 5 button 4",
    "joystick 5 button 5",
    "joystick 5 button 6",
    "joystick 5 button 7",
    "joystick 5 button 8",
    "joystick 5 button 9",
    "joystick 5 button 10",
    "joystick 5 button 11",
    "joystick 5 button 12",
    "joystick 5 button 13",
    "joystick 5 button 14",
    "joystick 5 button 15",
    "joystick 5 button 16",
    "joystick 5 button 17",
    "joystick 5 button 18",
    "joystick 5 button 19",
    "joystick 6 button 0",
    "joystick 6 button 1",
    "joystick 6 button 2",
    "joystick 6 button 3",
    "joystick 6 button 4",
    "joystick 6 button 5",
    "joystick 6 button 6",
    "joystick 6 button 7",
    "joystick 6 button 8",
    "joystick 6 button 9",
    "joystick 6 button 10",
    "joystick 6 button 11",
    "joystick 6 button 12",
    "joystick 6 button 13",
    "joystick 6 button 14",
    "joystick 6 button 15",
    "joystick 6 button 16",
    "joystick 6 button 17",
    "joystick 6 button 18",
    "joystick 6 button 19",
    "joystick 7 button 0",
    "joystick 7 button 1",
    "joystick 7 button 2",
    "joystick 7 button 3",
    "joystick 7 button 4",
    "joystick 7 button 5",
    "joystick 7 button 6",
    "joystick 7 button 7",
    "joystick 7 button 8",
    "joystick 7 button 9",
    "joystick 7 button 10",
    "joystick 7 button 11",
    "joystick 7 button 12",
    "joystick 7 button 13",
    "joystick 7 button 14",
    "joystick 7 button 15",
    "joystick 7 button 16",
    "joystick 7 button 17",
    "joystick 7 button 18",
    "joystick 7 button 19",
    "joystick 8 button 0",
    "joystick 8 button 1",
    "joystick 8 button 2",
    "joystick 8 button 3",
    "joystick 8 button 4",
    "joystick 8 button 5",
    "joystick 8 button 6",
    "joystick 8 button 7",
    "joystick 8 button 8",
    "joystick 8 button 9",
    "joystick 8 button 10",
    "joystick 8 button 11",
    "joystick 8 button 12",
    "joystick 8 button 13",
    "joystick 8 button 14",
    "joystick 8 button 15",
    "joystick 8 button 16",
    "joystick 8 button 17",
    "joystick 8 button 18",
    "joystick 8 button 19",
    "joystick 9 button 0",
    "joystick 9 button 1",
    "joystick 9 button 2",
    "joystick 9 button 3",
    "joystick 9 button 4",
    "joystick 9 button 5",
    "joystick 9 button 6",
    "joystick 9 button 7",
    "joystick 9 button 8",
    "joystick 9 button 9",
    "joystick 9 button 10",
    "joystick 9 button 11",
    "joystick 9 button 12",
    "joystick 9 button 13",
    "joystick 9 button 14",
    "joystick 9 button 15",
    "joystick 9 button 16",
    "joystick 9 button 17",
    "joystick 9 button 18",
    "joystick 9 button 19",
    "joystick 10 button 0",
    "joystick 10 button 1",
    "joystick 10 button 2",
    "joystick 10 button 3",
    "joystick 10 button 4",
    "joystick 10 button 5",
    "joystick 10 button 6",
    "joystick 10 button 7",
    "joystick 10 button 8",
    "joystick 10 button 9",
    "joystick 10 button 10",
    "joystick 10 button 11",
    "joystick 10 button 12",
    "joystick 10 button 13",
    "joystick 10 button 14",
    "joystick 10 button 15",
    "joystick 10 button 16",
    "joystick 10 button 17",
    "joystick 10 button 18",
    "joystick 10 button 19",
    "joystick 11 button 0",
    "joystick 11 button 1",
    "joystick 11 button 2",
    "joystick 11 button 3",
    "joystick 11 button 4",
    "joystick 11 button 5",
    "joystick 11 button 6",
    "joystick 11 button 7",
    "joystick 11 button 8",
    "joystick 11 button 9",
    "joystick 11 button 10",
    "joystick 11 button 11",
    "joystick 11 button 12",
    "joystick 11 button 13",
    "joystick 11 button 14",
    "joystick 11 button 15",
    "joystick 11 button 16",
    "joystick 11 button 17",
    "joystick 11 button 18",
    "joystick 11 button 19",
    "joystick 12 button 0",
    "joystick 12 button 1",
    "joystick 12 button 2",
    "joystick 12 button 3",
    "joystick 12 button 4",
    "joystick 12 button 5",
    "joystick 12 button 6",
    "joystick 12 button 7",
    "joystick 12 button 8",
    "joystick 12 button 9",
    "joystick 12 button 10",
    "joystick 12 button 11",
    "joystick 12 button 12",
    "joystick 12 button 13",
    "joystick 12 button 14",
    "joystick 12 button 15",
    "joystick 12 button 16",
    "joystick 12 button 17",
    "joystick 12 button 18",
    "joystick 12 button 19",
    "joystick 13 button 0",
    "joystick 13 button 1",
    "joystick 13 button 2",
    "joystick 13 button 3",
    "joystick 13 button 4",
    "joystick 13 button 5",
    "joystick 13 button 6",
    "joystick 13 button 7",
    "joystick 13 button 8",
    "joystick 13 button 9",
    "joystick 13 button 10",
    "joystick 13 button 11",
    "joystick 13 button 12",
    "joystick 13 button 13",
    "joystick 13 button 14",
    "joystick 13 button 15",
    "joystick 13 button 16",
    "joystick 13 button 17",
    "joystick 13 button 18",
    "joystick 13 button 19",
    "joystick 14 button 0",
    "joystick 14 button 1",
    "joystick 14 button 2",
    "joystick 14 button 3",
    "joystick 14 button 4",
    "joystick 14 button 5",
    "joystick 14 button 6",
    "joystick 14 button 7",
    "joystick 14 button 8",
    "joystick 14 button 9",
    "joystick 14 button 10",
    "joystick 14 button 11",
    "joystick 14 button 12",
    "joystick 14 button 13",
    "joystick 14 button 14",
    "joystick 14 button 15",
    "joystick 14 button 16",
    "joystick 14 button 17",
    "joystick 14 button 18",
    "joystick 14 button 19",
    "joystick 15 button 0",
    "joystick 15 button 1",
    "joystick 15 button 2",
    "joystick 15 button 3",
    "joystick 15 button 4",
    "joystick 15 button 5",
    "joystick 15 button 6",
    "joystick 15 button 7",
    "joystick 15 button 8",
    "joystick 15 button 9",
    "joystick 15 button 10",
    "joystick 15 button 11",
    "joystick 15 button 12",
    "joystick 15 button 13",
    "joystick 15 button 14",
    "joystick 15 button 15",
    "joystick 15 button 16",
    "joystick 15 button 17",
    "joystick 15 button 18",
    "joystick 15 button 19",
    "joystick 16 button 0",
    "joystick 16 button 1",
    "joystick 16 button 2",
    "joystick 16 button 3",
    "joystick 16 button 4",
    "joystick 16 button 5",
    "joystick 16 button 6",
    "joystick 16 button 7",
    "joystick 16 button 8",
    "joystick 16 button 9",
    "joystick 16 button 10",
    "joystick 16 button 11",
    "joystick 16 button 12",
    "joystick 16 button 13",
    "joystick 16 button 14",
    "joystick 16 button 15",
    "joystick 16 button 16",
    "joystick 16 button 17",
    "joystick 16 button 18",
    "joystick 16 button 19",}

function Keylib.GetKey ()
    local keys_pressed = {}
    local n = 1
    for key in Keylib.Keys do
        if Input.GetKey(key) then
            keys_pressed[n] = key
        end
    end
    return keys_pressed
end 



return Keylib